---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-factory1-2367272-app
  name: test-factory1-2367272-service
  namespace: device-apps
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-factory1-2367272-app
---
