apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: test-factory1-2367272-configmap-app
  name: test-factory1-2367272-route
  namespace: device-apps
spec:
  host: "test-factory1-2367272.apps.demo.dcdevlab.net"
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  to:
    kind: Service
    name: test-factory1-2367272-service
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
