apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-factory1-2367272-pvc
  namespace: device-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
